spring:
  application:
    name: department-service
  datasource:
    url: jdbc:mariadb://localhost:3306/kotlin
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
server:
  port: 8091
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
ribbon:
  eureka:
    enabled: true