spring:
  application:
    name: dept
  datasource:
    url: jdbc:mariadb://localhost:3306/cemgiz
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
server:
  port: 8091
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka