spring:
  application:
    name: gateway
zuul:
  routes:
    dept:
      path: /dept/**
      serviceId: department-service
      stripPrefix: false
    emp:
      path: /emp/**
      serviceId: employee-service
      stripPrefix: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
    registerWithEureka: false
server:
  port: 8080
ribbon:
  eureka:
    enabled: true